name: Setup Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  generate-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.7
      - name: Commit wrapper
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add Gradle wrapper"
