name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # Use Gradle without wrapper (downloads Gradle 7.6.3)
      - name: Build release APK
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: "7.6.3"       # Compatible with AGP 7.4.x
          arguments: assembleRelease
          build-root-directory: "."

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/*.apk
          
