name: CI (disabled)
on:
  workflow_dispatch: {}   # only runs if you click Run manually

jobs:
  build:
    if: false             # disables the job completely
    runs-on: ubuntu-latest
    steps:
      - run: echo "Disabled until project setup is complete."